export const createEmptyBrand = () => ({
    name: '',
    email: '',
    password: '',
    phonenumber: '',
    role: 'brand',
    categories: [],
    page: [],
    brandlocation: [],
    logoURL: [],
    deliveryTime: '',
    description: '',
    isApproved: false,
    reviews: [],
    averageRating: 0,
    isActive: true,
});
